-- W6 — Admin, evals, observability and release-hardening schema.
ALTER TABLE review_queue_items ADD COLUMN IF NOT EXISTS source_id uuid REFERENCES sources(id) ON DELETE SET NULL, ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();
CREATE INDEX IF NOT EXISTS review_queue_filter_idx ON review_queue_items(state, queue_type, severity, source_id, created_at);
ALTER TABLE sources ADD COLUMN IF NOT EXISTS paused_at timestamptz, ADD COLUMN IF NOT EXISTS paused_by text, ADD COLUMN IF NOT EXISTS pause_reason text;
CREATE TABLE IF NOT EXISTS admin_action_audit (id bigserial PRIMARY KEY,actor text NOT NULL,action text NOT NULL,entity_type text NOT NULL,entity_id text NOT NULL,reason text NOT NULL,payload jsonb NOT NULL DEFAULT '{}'::jsonb,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS admin_action_audit_entity_idx ON admin_action_audit(entity_type, entity_id, created_at DESC);
CREATE TABLE IF NOT EXISTS source_anomalies (id bigserial PRIMARY KEY,source_id uuid NOT NULL REFERENCES sources(id) ON DELETE CASCADE,crawl_run_id uuid REFERENCES crawl_runs(id) ON DELETE SET NULL,severity conflict_severity NOT NULL,code text NOT NULL,message text NOT NULL,metrics jsonb NOT NULL DEFAULT '{}'::jsonb,detected_at timestamptz NOT NULL DEFAULT now(),resolved_at timestamptz,UNIQUE(source_id, crawl_run_id, code));
CREATE INDEX IF NOT EXISTS source_anomalies_open_idx ON source_anomalies(source_id, detected_at DESC) WHERE resolved_at IS NULL;
CREATE TABLE IF NOT EXISTS recrawl_decisions (id bigserial PRIMARY KEY,source_id uuid REFERENCES sources(id) ON DELETE SET NULL,hackathon_id uuid REFERENCES hackathons(id) ON DELETE CASCADE,priority numeric(8,6) NOT NULL CHECK (priority BETWEEN 0 AND 1),interval_seconds integer NOT NULL CHECK (interval_seconds > 0),reason text NOT NULL,inputs jsonb NOT NULL DEFAULT '{}'::jsonb,policy_version text NOT NULL,decided_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS recrawl_decisions_event_idx ON recrawl_decisions(hackathon_id, decided_at DESC);
CREATE TABLE IF NOT EXISTS eval_baselines (id bigserial PRIMARY KEY,suite_version text NOT NULL,baseline_name text NOT NULL,dataset_versions jsonb NOT NULL,metrics jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(suite_version, baseline_name));
CREATE TABLE IF NOT EXISTS eval_runs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),suite_version text NOT NULL,dataset_versions jsonb NOT NULL,metrics jsonb NOT NULL,breakdowns jsonb NOT NULL DEFAULT '{}'::jsonb,baseline_id bigint REFERENCES eval_baselines(id) ON DELETE SET NULL,passed boolean NOT NULL,git_sha text,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS eval_runs_created_idx ON eval_runs(created_at DESC);
CREATE TABLE IF NOT EXISTS release_gate_runs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),gate_name text NOT NULL,gate_version text NOT NULL,passed boolean NOT NULL,evidence jsonb NOT NULL DEFAULT '{}'::jsonb,git_sha text,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS release_gate_runs_name_idx ON release_gate_runs(gate_name, created_at DESC);
CREATE TABLE IF NOT EXISTS backup_manifests (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),backup_id text NOT NULL UNIQUE,database_sha256 char(64) NOT NULL,object_manifest_sha256 char(64) NOT NULL,object_count integer NOT NULL DEFAULT 0,started_at timestamptz NOT NULL,completed_at timestamptz NOT NULL,storage_uri text NOT NULL,encrypted boolean NOT NULL DEFAULT true,metadata jsonb NOT NULL DEFAULT '{}'::jsonb);