create extension if not exists pgcrypto;

create type public.post_status as enum (
  'draft', 'reviewing', 'approved', 'scheduled', 'publishing', 'published', 'failed'
);

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  created_at timestamptz not null default now()
);

create table public.app_settings (
  id boolean primary key default true check (id),
  timezone text not null default 'America/Sao_Paulo',
  publish_weekday smallint not null default 0 check (publish_weekday between 0 and 6),
  publish_hour smallint not null default 18 check (publish_hour between 0 and 23),
  generation_lead_hours smallint not null default 30 check (generation_lead_hours between 1 and 168),
  auto_publish boolean not null default false,
  updated_at timestamptz not null default now()
);

create table public.instagram_accounts (
  id uuid primary key default gen_random_uuid(),
  instagram_user_id text not null unique,
  username text not null,
  account_type text,
  access_token_encrypted text not null,
  token_expires_at timestamptz,
  is_active boolean not null default true,
  connected_by uuid references auth.users(id),
  connected_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.sources (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  url text not null unique,
  quality numeric(4,3) not null default 0.7 check (quality between 0 and 1),
  content_type text not null default 'news',
  enabled boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.articles (
  id uuid primary key default gen_random_uuid(),
  canonical_url text not null unique,
  title text not null,
  summary text not null default '',
  source_name text not null,
  source_quality numeric(4,3) not null default 0.7,
  content_type text not null default 'other',
  published_at timestamptz not null,
  popularity jsonb not null default '{}'::jsonb,
  raw jsonb not null default '{}'::jsonb,
  collected_at timestamptz not null default now()
);

create table public.story_clusters (
  id uuid primary key default gen_random_uuid(),
  week_start date not null,
  title text not null,
  summary text not null default '',
  topic text not null default 'other',
  source_urls jsonb not null default '[]'::jsonb,
  source_count integer not null default 1,
  source_quality numeric(4,3) not null default 0.7,
  popularity_score numeric(8,3) not null default 0,
  novelty_score numeric(4,3) not null default 0,
  clarity_score numeric(4,3) not null default 0,
  predicted_engagement numeric(5,4) not null default 0,
  score numeric(7,2) not null default 0,
  status text not null default 'candidate',
  created_at timestamptz not null default now(),
  unique (week_start, title)
);

create table public.cluster_articles (
  cluster_id uuid not null references public.story_clusters(id) on delete cascade,
  article_id uuid not null references public.articles(id) on delete cascade,
  primary key (cluster_id, article_id)
);

create table public.posts (
  id uuid primary key default gen_random_uuid(),
  week_start date not null unique,
  title text not null,
  caption text not null,
  status public.post_status not null default 'draft',
  selected_cluster_ids jsonb not null default '[]'::jsonb,
  features jsonb not null default '{}'::jsonb,
  review_report jsonb not null default '{}'::jsonb,
  scheduled_for timestamptz,
  published_at timestamptz,
  instagram_media_id text,
  publish_attempts integer not null default 0,
  last_error text,
  learning_applied_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.post_slides (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null references public.posts(id) on delete cascade,
  position smallint not null check (position between 1 and 10),
  layout text not null,
  content jsonb not null,
  created_at timestamptz not null default now(),
  unique (post_id, position)
);

create table public.post_metrics (
  id bigint generated by default as identity primary key,
  post_id uuid not null references public.posts(id) on delete cascade,
  captured_at timestamptz not null default now(),
  views integer not null default 0,
  reach integer not null default 0,
  likes integer not null default 0,
  comments integer not null default 0,
  saved integer not null default 0,
  shares integer not null default 0,
  follows integer not null default 0,
  profile_visits integer not null default 0,
  total_interactions integer not null default 0,
  engagement_score numeric(7,5) not null default 0
);

create table public.model_weights (
  feature text primary key,
  weight numeric(8,6) not null,
  sample_count integer not null default 0,
  updated_at timestamptz not null default now()
);

create table public.pipeline_runs (
  id uuid primary key default gen_random_uuid(),
  stage text not null,
  status text not null,
  details jsonb not null default '{}'::jsonb,
  error text,
  started_at timestamptz not null default now(),
  finished_at timestamptz
);

create index articles_published_at_idx on public.articles (published_at desc);
create index clusters_week_score_idx on public.story_clusters (week_start desc, score desc);
create index posts_status_schedule_idx on public.posts (status, scheduled_for);
create index metrics_post_capture_idx on public.post_metrics (post_id, captured_at desc);
create index pipeline_stage_started_idx on public.pipeline_runs (stage, started_at desc);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email)
  values (new.id, coalesce(new.email, ''))
  on conflict (id) do update set email = excluded.email;
  return new;
end;
$$;

create trigger on_auth_user_created
after insert or update of email on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger touch_settings before update on public.app_settings
for each row execute procedure public.touch_updated_at();
create trigger touch_instagram before update on public.instagram_accounts
for each row execute procedure public.touch_updated_at();
create trigger touch_posts before update on public.posts
for each row execute procedure public.touch_updated_at();

insert into public.app_settings (id) values (true) on conflict (id) do nothing;

insert into public.sources (name, url, quality, content_type) values
  ('Google DeepMind', 'https://deepmind.google/blog/rss.xml', 0.96, 'research'),
  ('Google AI', 'https://blog.google/technology/ai/rss/', 0.94, 'news'),
  ('MIT Technology Review AI', 'https://www.technologyreview.com/topic/artificial-intelligence/feed', 0.90, 'news'),
  ('VentureBeat AI', 'https://venturebeat.com/category/ai/feed/', 0.76, 'market'),
  ('arXiv cs.AI', 'https://export.arxiv.org/rss/cs.AI', 0.90, 'research'),
  ('arXiv cs.LG', 'https://export.arxiv.org/rss/cs.LG', 0.90, 'research'),
  ('Hugging Face Blog', 'https://huggingface.co/blog/feed.xml', 0.88, 'tool'),
  ('NVIDIA AI', 'https://blogs.nvidia.com/blog/category/deep-learning/feed/', 0.90, 'news')
on conflict (url) do nothing;

insert into public.model_weights (feature, weight) values
  ('popularity', 0.28), ('sourceCoverage', 0.17), ('sourceQuality', 0.14),
  ('novelty', 0.13), ('clarity', 0.10), ('research', 0.05),
  ('market', 0.04), ('tool', 0.04), ('regulation', 0.03), ('hasNumber', 0.02)
on conflict (feature) do nothing;

alter table public.profiles enable row level security;
alter table public.app_settings enable row level security;
alter table public.instagram_accounts enable row level security;
alter table public.sources enable row level security;
alter table public.articles enable row level security;
alter table public.story_clusters enable row level security;
alter table public.cluster_articles enable row level security;
alter table public.posts enable row level security;
alter table public.post_slides enable row level security;
alter table public.post_metrics enable row level security;
alter table public.model_weights enable row level security;
alter table public.pipeline_runs enable row level security;

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'profiles','app_settings','instagram_accounts','sources','articles','story_clusters',
    'cluster_articles','posts','post_slides','post_metrics','model_weights','pipeline_runs'
  ] loop
    execute format('create policy "admins can read %1$s" on public.%1$I for select to authenticated using (true)', table_name);
    execute format('create policy "admins can insert %1$s" on public.%1$I for insert to authenticated with check (true)', table_name);
    execute format('create policy "admins can update %1$s" on public.%1$I for update to authenticated using (true) with check (true)', table_name);
    execute format('create policy "admins can delete %1$s" on public.%1$I for delete to authenticated using (true)', table_name);
  end loop;
end $$;
